{
    "name": "Appointment",
    "summary": "This module helps you manage services, customers, and employees,and schedule appointments for them. It's ideal for businesses like clinics, salons, or any service-based company that needs appointment management.",
    "version": "17.0.1.0.0",
    "category": "Services",
    "license": "MIT",
    "website": "https://github.com/adelghaedi/appointment_module",
    "author": "AdelGhaedi",
    "installable": True,
    "application": True,
    "depends": [
        "base",
        "website",
        "hr",
        "mail",
    ],
    "data": [
        "security/group.xml",
        "security/ir.model.access.csv",
        "security/appointment_security.xml",
        "views/customer_view.xml",
        "views/employee_view.xml",
        "views/appointment_view.xml",
        "views/service_view.xml",
        "views/workfield_view.xml",
        "views/main_view.xml",
        "templates/service_list_template.xml",
        "templates/service_detail_template.xml",
        "templates/appointment_report_template.xml",
        "data/service_subtypes.xml",
    ],
    "controllers": [
        "controllers/service_controller.py",
    ]
}
